// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbdwhcbrfgmzyiuxwisu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZHdoY2JyZmdtenlpdXh3aXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODQyMzcsImV4cCI6MjA3MjY2MDIzN30.j5xgEYItuTMBkdpAxuHgsE9wvE5bOMdL-no33qUZ0fQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});